services:
  - type: web
    name: telegram-translator-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    runtime: python-3.10
    envVars:
      - key: TOKEN
        fromEnvVar: TOKEN
